# Generated by Django 4.2.1 on 2023-05-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ricetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('difficoltà', models.IntegerField(max_length=5)),
                ('tempo_svolgimento', models.FloatField()),
                ('numero_persone', models.IntegerField()),
                ('ingredienti', models.TextField()),
                ('istruzioni', models.TextField()),
            ],
        ),
    ]
