# Generated by Django 4.2.1 on 2023-05-26 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ricette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='ricetta',
            name='difficoltà',
        ),
        migrations.AddField(
            model_name='ricetta',
            name='difficolta',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ricetta',
            name='numero_persone',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Preferiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricette.ricetta')),
                ('Utente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testo', models.TextField()),
                ('Ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricette.ricetta')),
                ('Utente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
