# Generated by Django 4.2.1 on 2023-05-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0002_categoria_remove_ricetta_difficoltà_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricetta',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ricette.categoria'),
        ),
    ]
