# Generated by Django 4.2.1 on 2023-05-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0003_ricetta_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(choices=[('Antipasti', 'Antipasti'), ('Primi', 'Primi'), ('Secondi', 'Secondi'), ('Contorni', 'Contorni'), ('Dolci', 'Dolci')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ricetta',
            name='tempo_svolgimento',
            field=models.CharField(max_length=10),
        ),
    ]
