# Generated by Django 4.2.1 on 2023-06-01 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0004_alter_categoria_nome_alter_ricetta_tempo_svolgimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantita', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='ricetta',
            name='ingredienti',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ricette.ingrediente'),
        ),
    ]
