# Generated by Django 4.2.1 on 2023-06-01 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ricette', '0005_ingrediente_alter_ricetta_ingredienti'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='ricetta',
            name='ingredienti',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ricette_preferite',
            field=models.ManyToManyField(to='ricette.ricetta'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
