# Generated by Django 4.2.1 on 2023-06-03 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ricette', '0006_userprofile_alter_ricetta_ingredienti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricetta',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='ricette/immagini/'),
        ),
        migrations.AlterField(
            model_name='commento',
            name='Utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
