# Generated by Django 4.2.1 on 2023-06-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0007_ricetta_immagine_alter_commento_utente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricetta',
            name='immagine',
        ),
    ]
